name: ink-echo

services:
  api:
    build:
      context: ./server
      target: production
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - ./server/uploads:/app/uploads
    ports:
      - 3000:3000
    networks:
      - ink-echo

  frontend:
    build:
      context: ./client
      target: production
      args:
        VITE_API_SERVER_URL: https://api.${DOMAIN_NAME}/api
        VITE_API_ASSETS_URL: https://api.${DOMAIN_NAME}
    restart: unless-stopped
    ports:
      - 5173:5173
    networks:
      - ink-echo

  caddy:
    build:                     # we have used Dockerfile in caddy folder
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ink-echo
    depends_on:
      - api
      - frontend


volumes:
  caddy_data:
  caddy_config:
  
networks:
  ink-echo:
    driver: bridge